# Site settings
title: "Cocept - Boosting Bottom Lines by Building Better Business Tools"
description: "Welcome to Cocept, a Website Agency Based in Brighton, England that Specialises in Building Better Business Tools to Boost your Bottom Line. Find Out More."
url: "https://www.cocept.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:year/:title/

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom directories
include: ["_pages"]

# Defaults for blog posts
defaults:
  -
    scope:
      path: ""
    values:
      hero: false
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Max Mumford"
      author_link: "https://plus.google.com/+MaxMumford/"
  -
    scope:
      path: "design"
      type: "posts"
    values:
      layout: "post"
      category: "design"
  -
    scope:
      path: "development"
      type: "posts"
    values:
      layout: "post"
      category: "development"
  -
    scope:
      path: "portfolio"
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: "portfolio"
      category: "portfolio"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: "post"
  -
    scope:
      path: "side-projects"
      type: "posts"
    values:
      permalink: /:categories/:title/
      layout: "empty"
      category: "side-projects"

# Params
mailchimp_popup_delay: 20000
hero_line_1: We Help Boost <span class="disport">Bottom Lines</span>
hero_line_2: by building better websites
navigation: 
  - text: Home
    url: /
    icon: home
  - text: Portfolio
    url: /portfolio/
    icon: briefcase
  - text: Side Projects
    url: /side-projects/
    icon: heart
  - text: Blog
    url: /blog/
    icon: pencil
  - text: Contact
    url: /contact/
    icon: envelope
