# Site settings
title: MaxMakeDesign
url: "http://www.MaxMakeDesign.co.uk/"

# Build settings
markdown: kramdown

# Permalinks
permalink: /:categories/:year/:title

# Gems
gems:
  - jekyll-redirect-from

# Defaults for blog posts
defaults:
  -
    scope:
      type: "post"
      path: ""
    values:
      author: "Max Mumford"
      author_link: "https://plus.google.com/+MaxMumford/"
  -
    scope:
      path: "design"
      type: "post"
    values:
      layout: "post"
      author: "Max Mumford"
      category: "design"
  -
    scope:
      path: "development"
      type: "post"
    values:
      layout: "post"
      author: "Max Mumford"
      category: "development"
  -
    scope:
      path: "photography"
      type: "post"
    values:
      layout: "photography"
      author: "Max Mumford"
      category: "photography"

  -
    scope:
      path: "portfolio"
      type: "post"
    values:
      layout: "portfolio"
      author: "Max Mumford"
      category: "portfolio"
