# Site settings
title: "Cocept: Home of Max Mumford, Python and Umbraco Web Developer"
description: "Welcome to my digital home. Checkout my Development and Design work, articles, blog and photography."
url: "http://www.cocept.io"

# Build settings
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: /:categories/:year/:title

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom directories
include: ["_pages"]

# Defaults for blog posts
defaults:
  -
    scope:
      type: "posts"
      path: ""
    values:
      author: "Max Mumford"
      author_link: "https://plus.google.com/+MaxMumford/"
  -
    scope:
      path: "design"
      type: "posts"
    values:
      layout: "post"
      category: "design"
  -
    scope:
      path: "development"
      type: "posts"
    values:
      layout: "post"
      category: "development"
  -
    scope:
      path: "blog"
      type: "posts"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "portfolio"
      type: "posts"
    values:
      layout: "portfolio"
      category: "portfolio"

# prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'http://cocept.github.io'
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _drafts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
