# Site settings
title: "Cocept: Website Design & Development Agency in Brighton"
description: "Welcome to Cocept, a website design & development agency based in Brighton, UK"
url: "http://www.cocept.io"

# Build settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:categories/:year/:title

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom directories
include: ["_pages"]

# Defaults for blog posts
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Max Mumford"
      author_link: "https://plus.google.com/+MaxMumford/"
  -
    scope:
      path: "design"
      type: "posts"
    values:
      layout: "post"
      category: "design"
  -
    scope:
      path: "development"
      type: "posts"
    values:
      layout: "post"
      category: "development"
  -
    scope:
      path: "portfolio"
      type: "posts"
    values:
      permalink: /:categories/:title
      layout: "portfolio"
      category: "portfolio"
  -
    scope:
      path: "showcase"
      type: "posts"
    values:
      permalink: /:categories/:title
      layout: "empty"
      category: "showcase"
