# Site settings
title: "MaxMakeDesign: Home of Max Mumford, UX & Web Designer"
description: "Welcome to my digital home. Checkout my User Experience and Web Design work, design articles, blog and photography."
url: "http://www.maxmakedesign.co.uk"

# Build settings
markdown: kramdown

# Permalinks
permalink: /:categories/:year/:title

# Gems
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Custom directories
include: ["_pages"]

# Defaults for blog posts
defaults:
  -
    scope:
      type: "post"
      path: ""
    values:
      author: "Max Mumford"
      author_link: "https://plus.google.com/+MaxMumford/"
  -
    scope:
      path: "design"
      type: "post"
    values:
      layout: "post"
      category: "design"
  -
    scope:
      path: "development"
      type: "post"
    values:
      layout: "post"
      category: "development"
  -
    scope:
      path: "blog"
      type: "post"
    values:
      layout: "post"
      category: "blog"
  -
    scope:
      path: "portfolio"
      type: "post"
    values:
      layout: "portfolio"
      category: "portfolio"

# prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'http://maxmumford.github.io'
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _drafts:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
