# Site settings
title: MaxMakeDesign
email: maxmumford@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: ""
url: "http://localhost"
twitter_username: MaxMakeDesign
github_username: maxmumford

# Build settings
markdown: kramdown
permalink: pretty

# Gems
gems:
  - jekyll-redirect-from

# Defaults for blog posts
defaults:
  -
    scope:
      path: "design"
      type: "post"
    values:
      layout: "design"
      author: "Max Mumford"
      category: "design"
  -
    scope:
      path: "development"
      type: "post"
    values:
      layout: "development"
      author: "Max Mumford"
      category: "development"